spring:
  profiles:
    active: local

orders:
  username: ordersLocalUser
  password: ordersLocalPass

---

spring:
  profiles:
    active: prod

orders:
  username: ordersProdUser
  password: ordersProdPass